# SP Lightning Talk: Boolean numpy arrays and np.newaxis

A Boolean numpy array is a numpy array with true/false values

In [17]:
import numpy as np
A = np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]])
print(A == 4) #Print the Boolean elements of a result array

[[False False False  True]
 [False False False False]
 [False False False False]]


You can combine Boolean arrays using logical operators

In [6]:
#Test which elements of A are not divisible by 2

B = ~(A%2 == 0) 

print('array A:\n{}\n'.format(A))
print('array B:\n{}'.format(B))

array A:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

array B:
[[ True False  True False]
 [ True False  True False]
 [ True False  True False]]


Indexing with a Boolean array: 

Boolean arrays can be used to select elements of other numpy arrays. If A is any numpy array and C is a boolean array of the same dimensions then A[C] selects all elements of A for which the corresponding value of C is True.

In [7]:
#Test which elements of A are even

C = (A%2 == 0) 
print(C)

[[False  True False  True]
 [False  True False  True]
 [False  True False  True]]


In [8]:
# select all even elements of the array A

print(A[C]) 

[ 2  4  6  8 10 12]


Add dimensions to an array using numpy.newaxis

newaxis increases the dimension of an existing array by one more dimension. (eg. a 1D array will become a 2D array, a 2D array will become a 3D array).

In [19]:
#Eg. try adding two numpy arrays with different dimensions

D = np.array([1, 2, 3, 4, 5])
E = np.array([5, 4, 3])

In [16]:
#use np.newaxis to increase the dimension of one array so that these can be added

D_new = D[:, np.newaxis]

print (D_new+E)

[[ 6  5  4]
 [ 7  6  5]
 [ 8  7  6]
 [ 9  8  7]
 [10  9  8]]
